### ISSUE TITLE
Feature Request: HP Bar of Pet's Target

### ISSUE THREAD

**Issue by NerfOnline** [m4thmatic/PetMe#1]
I love the beastmaster focus of this addon! Thank you for your work :) I did want to request what I said in the title. Currently, the addon PetInfo does this, but I'd love to replace it with this one if we get that feature in the future. Thank you for your consideration!

**Comment by m4thmatic** [comment]
Yeah, it's been on my to-do list. I actually already have the functionality coded and was just testing it out before committing the update. It should be available later this evening.
