### ISSUE TITLE
Compact version?

### ISSUE THREAD

**Issue by Cohibaxi** [m4thmatic/PetMe#2]
Hello, I play on a smaller resolution so naturally alot of addons show up very large on my screen. Since I solo alot on BST and even on /BST, the charm duration information is very valuable to me but I was wondering if it is easily possible to have a compact window option to only show the "Pet Duration" section as highlighted below, showing that info in a small box by itself? Ty for reading

![tempsnip](https://github.com/m4thmatic/PetMe/assets/86850162/792f56ed-9461-4dc6-ab67-56dc7c883bc2)

**Comment by m4thmatic** [comment]
Should be fairly easy. Will add it to the todo list.

**Comment by Cohibaxi** [comment]
Awesome! Ty

**Comment by m4thmatic** [comment]
This capability has been added as part of v1.0.0.
