### ISSUE TITLE
checking stop working

### ISSUE THREAD

**Issue by Austlight** [m4thmatic/PetMe#4]
not sure what it is but after a while i'm unable to check mobs or other players but unloading petme and reloading fixes the issue but not sure what making it stop the function petme itself is still works fine while this is going on as well.

**Comment by m4thmatic** [comment]
I noticed this happen to me once, shortly after this issue was posted. Have been unable to replicate since then. Keeping it open for the time being, and will continue to monitor.

**Comment by m4thmatic** [comment]
This issue (as well as a couple of other related edge cases) has been resolved as of 2.0.3.
